"""states


Revision ID: 445863b33b99
Revises: c26f3f711c90
Create Date: 2024-02-05 20:41:01.536431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445863b33b99'
down_revision = 'c26f3f711c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('national_parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('states', sa.String(), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('national_parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('states')

    # ### end Alembic commands ###
